# Generated by Django 2.1.5 on 2019-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='local',
            field=models.CharField(max_length=255),
        ),
    ]
